name: gatuno
services:
  web:
    image: gatuno-web
    container_name: gatuno-web
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - API_URL=${API_URL:-http://localhost:3000}
    networks:
      - gatuno-net

networks:
  gatuno-net:
    external: true
