name: gatuno
services:
  web:
    image: gatuno-web
    container_name: gatuno-web
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - API_URL=${API_URL:-http://localhost:3000}
    networks:
      - gatuno-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G

networks:
  gatuno-net:
    external: true
