# syntax=docker/dockerfile:1.4
ARG NODE_VERSION=24.11.1

FROM node:${NODE_VERSION}-bookworm-slim AS base
WORKDIR /usr/src/app

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

ENV NG_CLI_ANALYTICS=false

COPY . .

CMD ["npm", "run", "start:docker"]
