FROM node:22-alpine AS base
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

FROM node:22-alpine AS production
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .

CMD ["npm", "run", "start:docker"]
