FROM node:24.11.1-alpine AS base
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

ENV NG_CLI_ANALYTICS=false

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

CMD ["npm", "run", "start:docker"]
