ARG NODE_VERSION=24.11.1

FROM node:${NODE_VERSION}-alpine AS builder

WORKDIR /usr/src/app

ENV NG_CLI_ANALYTICS=false

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:${NODE_VERSION}-alpine AS runtime

WORKDIR /usr/src/app

ENV NODE_ENV=production

USER node

COPY --chown=node:node --from=builder /usr/src/app/dist ./dist

EXPOSE 4000

CMD ["node", "dist/front/server/server.mjs"]
