const fs = require('node:fs');
const path = require('node:path');

const iconsDir = path.join(__dirname, '..', 'public', 'assets', 'icons');
const outputFilePath = path.join(
	__dirname,
	'..',
	'src',
	'app',
	'core',
	'constants',
	'icons.constant.ts',
);

if (!fs.existsSync(iconsDir)) {
	console.error(`Directory not found: ${iconsDir}`);
	process.exit(1);
}

const files = fs.readdirSync(iconsDir).filter((file) => file.endsWith('.svg'));
let constantContent = `// Auto-generated by scripts/build-icons.js
// Do not edit this file manually. Add/remove SVGs in public/assets/icons/

export const APP_ICONS: Record<string, string> = {
`;

files.forEach((file) => {
	const iconName = file.replace('.svg', '');
	let svgContent = fs.readFileSync(path.join(iconsDir, file), 'utf8');

	// Clean the SVG content to be a single inline string
	svgContent = svgContent
		.replace(/\r?\n|\r/g, '') // Remove newlines
		.replace(/'/g, "\\'") // Escape single quotes
		.replace(/\s+/g, ' ') // Collapse multiple spaces
		.replace(/>\s+</g, '><') // Remove space between tags
		.trim();

	constantContent += `\t'${iconName}': '${svgContent}',\n`;
});

constantContent += `};\n`;

fs.writeFileSync(outputFilePath, constantContent, 'utf8');
console.log(
	`Successfully generated icons.constant.ts with ${files.length} icons.`,
);
