name: Run Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-frontend:
        runs-on: ubuntu-latest
        env:
            CHROME_BIN: /usr/bin/google-chrome-stable
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24.11.1'
                  cache: 'npm'
                  cache-dependency-path: ./package-lock.json

            - name: Install Google Chrome for Headless Tests
              run: |
                  sudo apt-get update
                  wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                  echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
                  sudo apt-get update
                  sudo apt-get install -y google-chrome-stable
              env:
                  DEBIAN_FRONTEND: noninteractive

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm run test:headless

            - name: Build
              run: npm run build
